libs/dev-tools/src/cli/wasm/list.ts
libs/dev-tools/src/cli/wasm/show.ts
libs/dev-tools/src/lib/services/signer.ts

We missed a couple of cases in the previous PR.
Add a better error message when there is no core contract registered on the chain, and update some WASM commands to match the changes on chain.
Built the CLI and tested list, show, and upload commands.
Fixes issues introduced in #65

Update wasm CLI to match new proto messages

---

libs/as-sdk-integration-tests/assembly/http.ts
libs/as-sdk-integration-tests/assembly/index.ts
libs/as-sdk-integration-tests/src/http.test.ts
libs/as-sdk/assembly/http.ts
libs/as-sdk/assembly/json-utils.ts
libs/as-sdk/assembly/proxy-http.ts

Allow users to make Oracle Programs that utilise POST bodies.
The Uint8Array/Bytes we used previously were not correctly serialised when moving from the VM to the host. By converting them to a simple `u8[]` we also mimick the way back more closely.
Added a test case which failed initially.
Closes: #72

Correctly serialise request bodies

---

libs/as-sdk-integration-tests/src/tallyvm.test.ts
libs/as-sdk/assembly/tally.ts

Makes it simpler to work with Reveals
Convert `u8[]` to `Bytes` 
`bun run test` works after a modification in the expected result (Bytes returns a different shape then u8[])

ref(tally): use Bytes instead of u8 for the RevealResult

---

.github/workflows/pull_request.yml
libs/as-sdk-integration-tests/assembly/hex.ts
libs/as-sdk-integration-tests/assembly/index.ts
libs/as-sdk-integration-tests/src/hex.test.ts
libs/as-sdk/assembly/hex.ts
libs/as-sdk/assembly/process.ts

Fix issues we were having converting to and from hex.
For values that took up less than 2 characters when encoded the old implementation did not correctly pad with zero.
Added unit test that failed before implementing the fix.
N.A.

as-sdk: Correctly encode hex

---

libs/as-sdk/assembly/bindings/seda_v1.ts
libs/as-sdk/assembly/http.ts
libs/as-sdk/assembly/proxy-http.ts
libs/vm/src/vm-imports.ts

Allows users to set an expected public key, when calling the proxy. 
* Add extra parameter to set a public key

feat(sdk): add ability to set a expected public key on proxy calls

---

README.md
libs/as-sdk-integration-tests/assembly/bytes.ts
libs/as-sdk-integration-tests/assembly/http.ts
libs/as-sdk-integration-tests/assembly/index.ts
libs/as-sdk-integration-tests/assembly/proxy-http.ts
libs/as-sdk-integration-tests/assembly/vm-tests.ts
libs/as-sdk-integration-tests/src/bytes.test.ts
libs/as-sdk-integration-tests/src/http.test.ts
libs/as-sdk/README.md
libs/as-sdk/assembly/bytes.ts
libs/as-sdk/assembly/http.ts
libs/as-sdk/assembly/promise.ts
libs/as-sdk/assembly/proxy-http.ts
libs/as-sdk/package.json

Make common usage patterns require less code.
Add a simple getter on the HttpResponse to quickly check whether the response status falls in the 200-299 inclusive range.
Also add some JSON convenience methods to `Bytes` to quickly (de)serialise so the user doesn't have to do the string conversion manually.
Added and updated existing integration tests.
N.A.

More SDK improvements

---

libs/as-sdk-integration-tests/project.json
libs/dev-tools/build.ts
libs/dev-tools/package.json
package.json

Fixes an issue where the user had to know the exact location of the source file to get a successful execution of the VM, but that caused TypeScript to complain.
Previously the compiled bundle caused problems when attempting to call executeDrWasm or executeTallyWasm, as it tried to resolve a path based on the location of the bundle, not the @seda-protocol/vm index file. By externalising the dependency it should now work correctly while retaining the type information.
With `npm pack` and manually changing the `node_modules` of the request starter kit
N.A.

Allow importing execute functions from bundle

---

libs/as-sdk-integration-tests/assembly/bytes.ts
libs/as-sdk-integration-tests/assembly/crypto.ts
libs/as-sdk-integration-tests/assembly/index.ts
libs/as-sdk-integration-tests/assembly/proxy-http.ts
libs/as-sdk-integration-tests/src/bytes.test.ts
libs/as-sdk-integration-tests/src/crypto.test.ts
libs/as-sdk-integration-tests/src/proxy-http.test.ts
libs/as-sdk/assembly/bindings/seda_v1.ts
libs/as-sdk/assembly/bytes.ts
libs/as-sdk/assembly/crypto.ts
libs/as-sdk/assembly/index.ts
libs/as-sdk/assembly/proxy-http.ts
libs/as-sdk/package.json
libs/dev-tools/package.json
libs/vm/package.json
libs/vm/src/vm-imports.ts

Allow users to implement data proxy signature verification in their Oracle Programs, as well as convenience methods to make this easier.
Add Bytes.concat convenience methods. Both a static variant as well as a method on the instance.
Add keccak256 import binding to the VM.
Add keccak256 hashing function to the SDK utilising the import.
Add method to generate the message for a proxy http fetch.
Added tests for all new functions. Verified the message generation with the data-proxy-sdk method.
N.A.

Signature verification

---

libs/dev-tools/src/index.ts
libs/dev-tools/src/lib/services/dr/await-data-result-bundle.ts
libs/dev-tools/src/lib/services/dr/get-data-request-bundle-status.ts
libs/dev-tools/src/lib/services/dr/get-data-request-status.ts
libs/dev-tools/src/lib/services/dr/get-data-result-bundle.ts
libs/dev-tools/src/lib/services/dr/get-data-result.ts
libs/dev-tools/src/lib/services/dr/post-and-await-data-request-bundle.ts
libs/dev-tools/src/lib/services/dr/post-data-request-bundle.ts

Make it easier to post several DRs in one go.
Added `Bundle` versions of all DR related methods.
I used the following script to test the `postAndAwaitDataRequestBundle`
```ts
import { Signer, buildSigningConfig, postAndAwaitDataRequestBundle } from "./";
async function main() {
const signingConfig = buildSigningConfig({});
const signer = await Signer.fromPartial(signingConfig);
console.log("Posting and waiting for results, this may take a lil while..");
const result = await postAndAwaitDataRequestBundle(
signer,
[
"eth-usdc",
"sol-btc",
].map((pair) => {
return {
consensusOptions: {
method: "none",
},
oracleProgramId:
"470fca08d461761f16d42a357d04732524c85f00e32e0360a246a9396a9d2fc0",
drInputs: Buffer.from(pair),
tallyInputs: Buffer.from([]),
memo: Buffer.from(`pair_${pair}_${new …
```

Add support for DR bundle methods

---

libs/dev-tools/package.json
libs/dev-tools/src/cli/oracle-program/upload.ts

Less confusing.
Instead of a hex representation of a hex string.
Built the CLI and uploaded an existing WASM.
N.A.

fix(dev-tools): display the oracle program id as hex

---

libs/proto-messages/gen/sedachain/pubkey/v1/pubkey.ts
libs/proto-messages/package.json
libs/proto-messages/proto/sedachain/batching/v1/batching.proto
libs/proto-messages/proto/sedachain/batching/v1/query.proto
libs/proto-messages/proto/sedachain/pubkey/v1/pubkey.proto
package.json

Update protobuf to latest version

---

libs/dev-tools/package.json
libs/dev-tools/src/lib/services/dr/create-dr-input.ts
libs/dev-tools/src/lib/services/dr/get-data-result.ts
libs/proto-messages/gen/index.ts
libs/proto-messages/gen/sedachain/batching/v1/batching.ts
libs/proto-messages/gen/sedachain/batching/v1/genesis.ts
libs/proto-messages/gen/sedachain/batching/v1/query.ts
libs/proto-messages/package.json
libs/proto-messages/proto/sedachain/batching/v1/batching.proto
libs/proto-messages/proto/sedachain/batching/v1/genesis.proto
libs/proto-messages/proto/sedachain/batching/v1/query.proto

Stay up to date with the latest changes of the protocol
bump proto-messages version to `v0.4.0-dev.3`
bump dev-tools version to `v0.0.15`
Tested by deploying the latest contract on a local chain running the latest version of main. Posting a DR succeeds, and the result can be queried:
```ts
{
version: "0.0.1",
drId: "150ac588497094491516feecd60318053c7a5f27f89e18fce247140e3e446f19",
drBlockHeight: 172n,
consensus: false,
exitCode: 200,
result: "0x6e656564203120636f6d6d6974733b2072656365697665642030",
resultAsUtf8: "need 1 commits; received 0",
blockHeight: 182n,
blockTimestamp: 2024-11-28T12:49:48.000Z,
gasUsed: 0n,
paybackAddress: "seda_sdk",
sedaPayload: "",
}
```
The DRs just timed out, as I didn't bother running an overlay node locally and uploading oracle programs.
Closes: #110

Update DR fields

---

libs/as-sdk-integration-tests/src/tallyvm.test.ts
libs/as-sdk/assembly/tally.ts
libs/as-sdk/package.json
libs/dev-tools/package.json
libs/dev-tools/src/lib/testing/create-mock-reveal.ts

On the protocol side it has always been a uint64, we just never noticed since our oracle programs didn't use the field.
N.A.
Updated the unit test.
N.A.

Reveal gas_used is now a uint64

---

libs/dev-tools/src/lib/services/dr/consensus-filter.test.ts
libs/dev-tools/src/lib/services/dr/consensus-filter.ts
libs/dev-tools/src/lib/services/dr/create-dr-input.ts

Update inputs to be compatible with the latest changes on chain
Update std-dev filter options and serialisation so it matches what is available on chain.
Set the default gasPrice to a sensible value. I'm open to different values, I just saw this come up the most in our models/discussions and I wanted to create the PR so it's off my mental todo list 😛 
Set the default tally gas limit to the current limit on chain.
Posted DRs to a local network.
Closes: #124

Update DR input options

---

libs/vm/package.json
libs/vm/src/index.ts
libs/vm/src/worker.ts

Expose Worker as a function so it can be used to create your own Worker instance. This is required in order to make the overlay node embed the worker in the single binary.

refactor(vm): expose worker and allow worker as a parameter

---

libs/as-sdk/package.json

Even though we don't officially recommend it anymore we can at least publish the latest working version. :)

chore(as-sdk): bump version to v1.0.0-rc.1

---

Cargo.lock
libs/rs-sdk/sdk/Cargo.toml
libs/rs-sdk/sdk/src/log.rs

Added more gas-efficient logging macros as alternatives to standard print macros. Also fixed missing `Write` trait import in debug macro for better developer experience.
- Added `log!` and `elog!` macros using `write_all` for better gas efficiency
- Added `use std::io::Write` in debug macro to avoid requiring manual import
- Added documentation and examples for all macros
Run the following to verify macros work:
```bash
cargo test -p seda-sdk-rs -- --nocapture
```
N/A

feat(rs-sdk): add log and elog macros

---

libs/dev-tools/package.json
libs/dev-tools/src/lib/services/dr/get-data-result.ts

The schema was expecting a bigint but a string was given. We convert the `gasUsed` to bigint. :)

fix(dev-tools): convert string gas used to bigint

---

bun.lock
libs/dev-tools/package.json
libs/vm/package.json
libs/vm/src/vm.ts
libs/wasm-integration-tests/tests/universal/test-vm.test.ts
package.json

There was a memory leak in the `@wasmer/wasi` package. This package used native code to implement all WASI handlers. Only this was slowly increasing our memory usage. We chose a more lightweight option implemented in JavaScript which shows a lower memory footprint.
Replace Wasmer with uWasi
All tests passes (`bun run test`)

feat(vm): use uwasi instead of wasmer

---

libs/vm/src/data-request-vm-adapter.ts

Prevent issues where an emtpy body gets serialised as `[]`, which then becomes a body.
N.A.
Tests pass and the data proxy flow works for get requests.
N.A.

Do not sent empty bodies in HTTP requests

---

libs/dev-tools/package.json
libs/dev-tools/src/lib/services/dr/create-dr-input.ts
libs/dev-tools/src/lib/services/dr/post-data-request-bundle.ts
libs/dev-tools/src/lib/services/dr/post-data-request.ts
libs/dev-tools/src/lib/services/get-dr-config.ts

Now that we're imposing limits on the DR fields it's nice for developers to see they're hitting the limits before trying to submit the DR.
We first fetch the DR config from the contract before converting the inputs.
Tested in the DR playground by locally linking to the dev-tools package.
N.A.

Check DR attribute limits before posting

---

README.md
libs/rs-sdk-integration-tests/src/main.rs
libs/rs-sdk-integration-tests/src/tally.rs
libs/rs-sdk/README.md
libs/rs-sdk/sdk/Cargo.toml
libs/rs-sdk/sdk/src/hashmap.rs
libs/rs-sdk/sdk/src/lib.rs
libs/vm/package.json
libs/vm/src/imports/import-utils.ts
libs/vm/src/imports/wasi/args_get.ts
libs/vm/src/imports/wasi/environ_get.ts
libs/vm/src/imports/wasi/fd_write.ts
libs/vm/src/imports/wasi/random_get.ts
libs/wasm-integration-tests/tests/rs-sdk/tally-determinism.test.ts

Provide alternatives to developers for `HashMap` in the tally phase.
Wrap the default `HashMap` with a custom hash builder that does not rely on a random seed. No idea if this is the best way to do this though 😬 
Updated the VM to make any wasi import errors more explicit. 
Added tests that confirm the regular HashMap fails and our wrapper works.
Closes: #175

Hashmap limitations

---

Cargo.toml
libs/rs-sdk/README.md
libs/rs-sdk/sdk/Cargo.toml
libs/rs-sdk/sdk/src/lib.rs

So that panics in rust don't reveal the user's paths.
- Uses `ctor` to register the function to run before main.
- Downcasts the panic, `std::panic::PanicHookInfo`, payload to a String if possible otherwise just puts the message `<panic>`. The panic message if it can't be downcasted to a string is not very helpful. Not sure if we could do any better though.
> ![NOTE] This does effect panic messages that would occur from any crate.
What it looked like before with a panic in the wasm rust code itself:
A panic in the wasm rust code itself after:
What it looked like before with a panic from the sdk bubbling up:
A panic from the sdk bubbling up after:
Closes #182.

feat(rs-sdk): don't reveal path info in panics

---

libs/rs-sdk/README.md
libs/rs-sdk/sdk/Cargo.toml
libs/rs-sdk/sdk/src/bytes.rs
libs/rs-sdk/sdk/src/errors.rs
libs/rs-sdk/sdk/src/hashmap.rs
libs/rs-sdk/sdk/src/http.rs
libs/rs-sdk/sdk/src/keccak256.rs
libs/rs-sdk/sdk/src/lib.rs
libs/rs-sdk/sdk/src/log.rs
libs/rs-sdk/sdk/src/process.rs
libs/rs-sdk/sdk/src/promise.rs
libs/rs-sdk/sdk/src/promise_actions.rs
libs/rs-sdk/sdk/src/proxy_http_fetch.rs
libs/rs-sdk/sdk/src/raw.rs
libs/rs-sdk/sdk/src/secp256k1.rs
libs/rs-sdk/sdk/src/tally.rs
libs/rs-sdk/sdk/src/vm_modes.rs

So when we publish the crate to `crates.io` the `rust` docs follow the `rust` docs standard, and build.
- Adds the `crates.io` and `docs.rs` badges to the rs sdk readme.
- Fixes some existing rust docs to compile:
- when cargo docs is run
- have running tests where they can
- have proper paths and etc in the examples
- Fixes some macros:
- Debug macro fails if not used in a function that returns a convertible result type.
- Macro to generate JSON types now works.
- De-complicates generic parse function- made the docs stuff happier and works the same way.
- Rust will now error if something is undocumented.
TLDR mostly doc changes, small other things that should not break compatibility at all,
docs will be generated once we publish on `crates.io`.
Running docs command and test command is …

docs: deny missing docs, fix macros + generic fn

---

libs/as-sdk-integration-tests/assembly/proxy-http.ts
libs/dev-tools/package.json
libs/dev-tools/src/lib/testing/test-oracle-program.ts
libs/rs-sdk-integration-tests/src/proxy_http.rs
libs/vm/package.json
libs/vm/src/data-request-vm-adapter.ts
libs/wasm-integration-tests/tests/universal/http.test.ts

So we can write tests for the proxy http fetch calls.
Adds a way to change the proxy gas cost, via a named argument.
If that is set and the existing proxy function is set it will mock the proxy fetch.
A few caveats:
- I reuse the same mock. IMO, this is fine since you can just match on the URL already. If we preferred it to be separate, LMK.
- In the mock proxy, I don't do header validations, it simply forwards the request to the normal http fetch action. I figured setting up identifies, etc. for testing could be annoying, but we could add that functionality in dev-tools for testing as well. So let me know if we prefer that as well.
Tested with the seda-example-ops repo locally and it works!
A few new tests added as well.
Closes #201

chore: Proxy http fetch
