sedaprotocol/seda-sdk

libs/dev-tools/package.json, libs/proto-messages/package.json
Dependency on base protobuf implementation was missing.
Add missing dependency.
Manually install the dependency in the project.
N.A.
=> Fix protobuf dependency

libs/as-sdk-integration-tests/assembly/http.ts, libs/as-sdk-integration-tests/assembly/index.ts, libs/as-sdk-integration-tests/assembly/proxy-http.ts, libs/as-sdk/assembly/bytes.ts, libs/as-sdk/assembly/process.ts, libs/as-sdk/assembly/promise.ts
Makes the developer experience better by introducing `isFulfilled()`, `isRejected()`, `unwrap()` and `unwrapRejected()`
* Introduce four new methods which removes the need to check for nulls
* `getInputs()` now returns `Bytes` allowing for easier to return strings
=> feat(promise): add unwrap and unwrapRejected

libs/as-sdk/package.json
=> chore(as-sdk): bump version to 0.0.5

libs/as-sdk/assembly/promise.ts, libs/as-sdk/package.json
There was a confusion where toString() was being used to parse custom structures. 
* replace toString with @ json
=> chore(sdk): remove toString on promise and replace with @json

libs/dev-tools/src/lib/services/dr/create-dr-input.ts
Set the gas limit to the same amount as the overlay node (default)
=> ref(gas-limit): set DEFAULT_GAS_LIMIT to 5_000_000_000

libs/as-sdk-integration-tests/assembly/bytes.ts, libs/as-sdk-integration-tests/assembly/index.ts, libs/as-sdk-integration-tests/src/bytes.test.ts, libs/as-sdk/assembly/bytes.ts
Allows users to convert bytes to and from a number
* add method toNumber<T>()
* add method fromNumber<T>()
Added a couple of tests
=> feat(bytes): add toNumber<T> and fromNumber<T>

libs/as-sdk/assembly/bytes.ts, libs/as-sdk/package.json
=> chore(as-sdk): bump version to v0.0.13

libs/dev-tools/package.json, libs/dev-tools/src/lib/services/dr/get-data-result.ts
Easier insights when logging the output to a console while keeping it easy to convert back to the raw bytes.
N.A.
Tested locally by changing the import of the example.
N.A.
=> Return result as hex and utf8

libs/proto-messages/gen/sedachain/batching/v1/genesis.ts, libs/proto-messages/gen/sedachain/batching/v1/query.ts, libs/proto-messages/package.json, libs/proto-messages/proto/sedachain/batching/v1/genesis.proto, libs/proto-messages/proto/sedachain/batching/v1/query.proto
=> chore(proto-messages): bump version to v0.4.0-dev.0-1

libs/dev-tools/package.json
Make it easy to interact with v0.5 :)
=> Bump dev-tools version to v0.5.0

libs/dev-tools/src/lib/services/dr/calculate-dr-funds.ts
This was not supposed to be in there in the first place!
=> chore(dev-tools): remove console statement

libs/as-sdk/package.json
=> chore(sdk): bump version to 0.0.18

.github/workflows/pull_request.yml, .github/workflows/push.yml
I forgot the push pipeline also builds and tests the project :D
=> chore(ci): install dependencies in both pipelines

libs/dev-tools/package.json
Make sure the correct proto messages are downloaded...
=> Bump proto-messages dependency

libs/vm/package.json
=> chore(vm): bump version to v0.1.0

libs/vm/package.json, libs/vm/src/data-request-vm-adapter.ts, libs/vm/src/services/read-stream.test.ts, libs/vm/src/services/read-stream.ts, libs/vm/src/tally-vm-adapter.ts, libs/vm/src/vm-imports.test.ts, libs/vm/src/vm-imports.ts, libs/vm/src/vm.ts
Disallow all WASI imports to be available
Introduce new option allowedImports where you can configure the WASI imports you want. The adapters already fill these in
`bun run test`
closes #137
=> feat(vm): limit the amount of WASI imports

libs/as-sdk/assembly/tally.ts, libs/dev-tools/src/lib/testing/create-mock-reveal.ts, libs/rs-sdk/sdk/src/tally.rs, libs/wasm-integration-tests/tests/universal/tally.test.ts
Update the reveal schema according to the changes on the contract and in the chain.
N.A.
Updated integration tests in this repo and in the chain
Chain: https://github.com/sedaprotocol/seda-chain/pull/526
Contract: https://github.com/sedaprotocol/seda-chain-contracts/pull/273
=> Update reveal schema

libs/dev-tools/src/lib/services/dr/consensus-filter.test.ts, libs/dev-tools/src/lib/services/dr/consensus-filter.ts
Be clear about what people can expect.
Rename the filter types, functions, etc.
Tests still pass.
N.A.
=> Rename std-dev filter to MAD

Cargo.lock, Cargo.toml, libs/dev-tools/package.json, libs/rs-sdk-integration-tests/Cargo.toml, libs/rs-sdk-integration-tests/src/main.rs, libs/rs-sdk-integration-tests/src/random_get.rs, libs/vm/package.json, libs/vm/src/imports/wasi/random_get.ts, libs/vm/src/metering.ts, libs/vm/src/vm-imports.ts, libs/wasm-integration-tests/tests/rs-sdk/infinite-loop.test.ts, libs/wasm-integration-tests/tests/rs-sdk/random-get.test.ts
Adds random_get support for the VM
=> feat(wasi): add random_get support

libs/dev-tools/package.json, libs/rs-sdk-integration-tests/src/main.rs, libs/vm/package.json, libs/vm/src/errors.ts, libs/vm/src/vm.ts, libs/wasm-integration-tests/tests/rs-sdk/errors.test.ts
Fix issue where stack traces where being shown in the stderr and on the explorer
=> fix(vm): fix issue where stack traces where shown in the stderr

bun.lock, libs/dev-tools/package.json, libs/vm/package.json, libs/vm/src/metering.ts, libs/vm/src/vm-imports.ts, libs/vm/src/vm.ts, libs/wasm-integration-tests/tests/rs-sdk/errors.test.ts, libs/wasm-integration-tests/tests/rs-sdk/infinite-loop.test.ts, libs/wasm-integration-tests/tests/universal/test-vm.test.ts, package.json
Improve gas metering performance.
See metering PR.
Tests still pass.
Closes: #158
=> Improve gas metering

Cargo.lock, libs/rs-sdk-integration-tests/src/random_get.rs, libs/rs-sdk/sdk/Cargo.toml, libs/rs-sdk/sdk/src/log.rs, libs/rs-sdk/sdk/src/process.rs, libs/rs-sdk/sdk/src/secp256k1.rs, libs/rs-sdk/sdk/src/tally.rs
Just some annoying clippy warnings.
=> chore(rs-sdk): fix clippy warnings

libs/dev-tools/package.json, libs/rs-sdk-integration-tests/src/infinite_loop.rs, libs/rs-sdk-integration-tests/src/main.rs, libs/vm/package.json, libs/vm/src/data-request-vm-adapter.ts, libs/vm/src/errors.ts, libs/vm/src/index.ts, libs/vm/src/services/wasm-module.ts, libs/vm/src/types/vm-adapter.ts, libs/vm/src/vm.ts, libs/vm/src/worker-host-communication.ts, libs/wasm-integration-tests/tests/rs-sdk/infinite-loop.test.ts
Added global time limits for http calls. This ensures that only a maximum amount of time is spent doing an http fetch. Otherwise the execution gets aborted
Had to modify quite a few components in order to make sure all data we want gets properly propagated when a global http fetch timeout occurs. 
* Added a new test for http global timeouts
=> feat(vm): added global http-timeouts

libs/dev-tools/package.json, libs/vm/package.json, libs/vm/src/data-request-vm-adapter.ts, libs/vm/src/metering.ts
The error timeout message was not correctly returned, now it is :)
=> fix(vm): fix issue where the timeout message was not correctly displayed

libs/dev-tools/package.json, libs/dev-tools/src/index.ts
I need it for serializing the consensus filter in the dr playground. :) 
Expose the encodeConsensusFilter function.
=> chore: expose encode consensus filter

LICENSE
=> chore: fix license header
